### ISSUE TITLE
Moving below "FAN_OFF_TEMP"

### ISSUE THREAD

**Issue by Dakurtz422** [hooperbill/fan-daemon#1]
Hi, I set "define FAN_OFF_TEMP 40" in fan-daemon.h built it and installed it, but when I check temp with "cat /sys/devices/virtual/thermal/thermal_zone*/temp" fan is moving (slow) even when temp is bellow 40. What could be the cause?

**Comment by hooperbill** [comment]
I apologize for the very slow response. There is a pending change that may resolve your issue and I would suggest taking a look at it.
